// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Fantastic_octo_bassoonML.Model
{
    public class ModelInput
    {
        [ColumnName("ItemID"), LoadColumn(0)]
        public string ItemID { get; set; }


        [ColumnName("Loccode"), LoadColumn(1)]
        public float Loccode { get; set; }


        [ColumnName("InQty"), LoadColumn(2)]
        public float InQty { get; set; }


        [ColumnName("OutQty"), LoadColumn(3)]
        public float OutQty { get; set; }


        [ColumnName("ItemType"), LoadColumn(4)]
        public string ItemType { get; set; }


        [ColumnName("TotalStockQty"), LoadColumn(5)]
        public float TotalStockQty { get; set; }


    }
}
